VERSION=`git describe --tags`
BUILDTIME=`date -u +%a,\ %d\ %b\ %Y\ %H:%M:%S\ GMT`

LDFLAGS=-ldflags "-w -s -X main.Version=${VERSION} -X 'main.Compiled=${BUILDTIME}'"

build:
	go fmt . ./lib/...
	go vet . ./lib/...
	go test . ./lib/...
	go install ${LDFLAGS} . ./lib/...

